[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "subdir"
description = "A subdirectory library"
requires-python = ">=3.9"
version = "0.0.0"
dependencies = [
  "requests~=2.24",
]
